
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// LINEDETAIL
export const CREATE_LINEDETAIL_SUCCESS = "CREATE_LINEDETAIL_SUCCESS";
export const DELETE_LINEDETAIL_SUCCESS = "DELETE_LINEDETAIL_SUCCESS";
export const GET_LINEDETAIL_SUCCESS = "GET_LINEDETAIL_SUCCESS";
export const LIST_LINEDETAIL_SUCCESS = "LIST_LINEDETAIL_SUCCESS";
export const UPDATE_LINEDETAIL_SUCCESS = "UPDATE_LINEDETAIL_SUCCESS";

// PURCHASEORDER
export const CREATE_PURCHASEORDER_SUCCESS = "CREATE_PURCHASEORDER_SUCCESS";
export const DELETE_PURCHASEORDER_SUCCESS = "DELETE_PURCHASEORDER_SUCCESS";
export const FINDBYPONUMBER_PURCHASEORDER_SUCCESS = "FINDBYPONUMBER_PURCHASEORDER_SUCCESS";
export const FINDBYPO_LINEDETAILS_PURCHASEORDER_SUCCESS = "FINDBYPO_LINEDETAILS_PURCHASEORDER_SUCCESS";
export const FINDBYPO_WEBORDERLEVEL_PURCHASEORDER_SUCCESS = "FINDBYPO_WEBORDERLEVEL_PURCHASEORDER_SUCCESS";
export const GET_PURCHASEORDER_SUCCESS = "GET_PURCHASEORDER_SUCCESS";
export const GETPO_LINEDETAILS_PURCHASEORDER_SUCCESS = "GETPO_LINEDETAILS_PURCHASEORDER_SUCCESS";
export const GETPO_WEBORDERLEVEL_PURCHASEORDER_SUCCESS = "GETPO_WEBORDERLEVEL_PURCHASEORDER_SUCCESS";
export const LIST_PURCHASEORDER_SUCCESS = "LIST_PURCHASEORDER_SUCCESS";
export const UPDATE_PURCHASEORDER_SUCCESS = "UPDATE_PURCHASEORDER_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// WEBORDERLEVEL
export const CREATE_WEBORDERLEVEL_SUCCESS = "CREATE_WEBORDERLEVEL_SUCCESS";
export const DELETE_WEBORDERLEVEL_SUCCESS = "DELETE_WEBORDERLEVEL_SUCCESS";
export const GET_WEBORDERLEVEL_SUCCESS = "GET_WEBORDERLEVEL_SUCCESS";
export const LIST_WEBORDERLEVEL_SUCCESS = "LIST_WEBORDERLEVEL_SUCCESS";
export const UPDATE_WEBORDERLEVEL_SUCCESS = "UPDATE_WEBORDERLEVEL_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
